name: Windows Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Install Yarn
      run: npm install -g yarn
      
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Apply patches
      run: yarn postinstall
      
    - name: Compile TypeScript
      run: yarn compile
      
    - name: Initialize Windows project
      run: npx react-native init-windows --template cpp-app --namespace APMWindows --overwrite
      
    - name: Build Windows app (Debug x64)
      run: npx react-native run-windows --arch x64 --release --no-launch
      
    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: windows-build-artifacts
        path: |
          windows/x64/Release/
          windows/AzusaPlayerMobile.Package/AppPackages/
        retention-days: 7