name: Windows Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Enable Corepack
      run: corepack enable
      
    - name: Install correct Yarn version
      run: corepack prepare yarn@4.9.1 --activate
      
    - name: Install dependencies
      run: yarn install --immutable
      
    - name: Apply patches
      run: yarn postinstall
      
    - name: Compile TypeScript
      run: yarn compile
      
    - name: Initialize Windows project
      run: npx react-native init-windows --template cpp-app --namespace APMWindows --overwrite
      
    - name: Fix Windows App SDK path issues
      run: |
        $windowsAppSdkPath = "C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.7.250401001"
        if (Test-Path $windowsAppSdkPath) {
          # Create missing architecture-specific directories
          New-Item -ItemType Directory -Path "$windowsAppSdkPath\lib\win10-" -Force
          New-Item -ItemType Directory -Path "$windowsAppSdkPath\runtimes\win-\native" -Force
          
          # Copy x64 files to the missing paths
          if (Test-Path "$windowsAppSdkPath\lib\win10-x64") {
            Copy-Item "$windowsAppSdkPath\lib\win10-x64\*" "$windowsAppSdkPath\lib\win10-" -Recurse -Force
          }
          if (Test-Path "$windowsAppSdkPath\runtimes\win-x64\native") {
            Copy-Item "$windowsAppSdkPath\runtimes\win-x64\native\*" "$windowsAppSdkPath\runtimes\win-\native" -Recurse -Force
          }
        }
        
        # Fix Hermes DLL path issue
        $hermesPath = "C:\Users\runneradmin\.nuget\packages\microsoft.javascript.hermes"
        $hermesVersion = Get-ChildItem $hermesPath -Directory | Select-Object -First 1 -ExpandProperty Name
        if ($hermesVersion) {
          $hermesDllPath = "$hermesPath\$hermesVersion\build\native\uwp"
          if (Test-Path "$hermesDllPath\x64\hermes.dll" -and !(Test-Path "$hermesDllPath\hermes.dll")) {
            Copy-Item "$hermesDllPath\x64\hermes.dll" "$hermesDllPath\hermes.dll" -Force
          }
        }
      
    - name: Build Windows app (Release x64)
      run: npx react-native run-windows --arch x64 --release --no-launch
      
    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: windows-build-artifacts
        path: |
          windows/x64/Release/
          windows/AzusaPlayerMobile.Package/AppPackages/
        retention-days: 7